# config/solr_wrapper_test.yml
# Note: If you're updating this file, it must be updated in a total of three places:
#   - .solr_wrapper
#   - config/solr_wrapper_test.yml
#   - config/travis/solr_wrapper_test.yml
version: 7.4.0
port: 8985
instance_dir: solr-test
download_dir: dep_cache
collection:
  persist: false
  dir: solr/config
  name: hydra-test
