language: ruby
cache: bundler
bundler_args: --without development debug
sudo: false
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JS=true
  matrix:
    - TEST_SUITE=mainfeature
    - TEST_SUITE=subfeature
    - TEST_SUITE=unit
before_install:
  - export PATH="$PATH:$(pwd)/fits"
services:
  - redis-server
before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "cp config/redis.yml.sample config/redis.yml"
  - "cp config/devise.yml.sample config/devise.yml"
  - "cp config/solr.yml.sample config/solr.yml"
  - "cp config/fedora.yml.sample config/fedora.yml"
  - "cp config/hydra-ldap.yml.sample config/hydra-ldap.yml"
  - redis-cli info
matrix:
  fast_finish: true
script:
  - "bundle exec rake scholarsphere:travis:$TEST_SUITE"
notifications:
  email:
    recipients:
      - "ul-dlt-hydra@lists.psu.edu"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
