language: ruby
cache: bundler
bundler_args: --without development debug
sudo: false
rvm:
  - 2.3.0
jdk:
  - oraclejdk8
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JS=true
  matrix:
    - TEST_SUITE=feature
    - TEST_SUITE=unit
    - TEST_SUITE=rubocop
before_install:
  - export PATH="$PATH:$(pwd)/fits"
services:
  - redis-server
before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "cp config/hydra-ldap.yml.sample config/hydra-ldap.yml"
  - "cp config/share_notify.yml.sample config/share_notify.yml"
  - redis-cli info
matrix:
  fast_finish: true
script:
  - "bundle exec rake scholarsphere:travis:$TEST_SUITE"
notifications:
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
