language: ruby
before_install:
  - sudo apt-get install libclamav-dev clamav-data
rvm:
  - "2.0.0"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - bundle exec rake scholarsphere:ci

before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
  - cp config/redis.yml.sample config/redis.yml
  - cp config/hydra-ldap.yml.sample config/hydra-ldap.yml
  - cp config/devise.yml.sample config/devise.yml
  - bundle exec rake scholarsphere:generate_secret

notifications:
  email:
    recipients:
      - "ul-dlt-applications@lists.psu.edu"
      - "michael@psu.edu"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
services:
  - redis-server
