language: ruby
cache:
  bundler: true
  directories:
    - "dep_cache"
bundler_args: --without development debug
sudo: false
rvm:
  - 2.3.0
jdk:
  - oraclejdk8
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JS=true
  matrix:
    - TEST_SUITE=feature
    - TEST_SUITE=unit
    - TEST_SUITE=rubocop
before_install:
  - export PATH="$PATH:$(pwd)/fits"
  - "mkdir -p dep_cache"
  - "pwd"
  - "ls -l dep_cache"
  - "cp config/travis/solr_wrapper_test.yml config/solr_wrapper_test.yml"
  - "cp config/travis/fcrepo_wrapper_test.yml config/fcrepo_wrapper_test.yml"
services:
  - redis-server
before_script:
  - "cp config/sample/database.yml config/database.yml"
  - "cp config/sample/hydra-ldap.yml config/hydra-ldap.yml"
  - "cp config/sample/share_notify.yml config/share_notify.yml"
  - "cp config/sample/initializers/qa.rb config/initializers/qa.rb"
  - redis-cli info
matrix:
  fast_finish: true
script:
  - "bundle exec rake scholarsphere:travis:$TEST_SUITE"
