---
file_system:
  :home: /Users/user/browse-everything/spec/internal
sky_drive:
  :client_id: CLIENT_ID
  :client_secret: CLIENT_SECRET
box:
  :client_id: CLIENT_ID
  :client_secret: CLIENT_SECRET
dropbox:
  :app_key: CLIENT_ID
  :app_secret: CLIENT_SECRET
google_drive:
  :client_id: "CLIENT_ID"
  :client_secret: "CLIENT_SECRET"


