development:
  host: dirapps.aset.psu.edu
  port: 389
  base: dc=psu,dc=edu
  group_base: dc=psu,dc=edu
test:  
  host: dirapps.aset.psu.edu
  port: 389
  base: dc=psu,dc=edu
  group_base: dc=psu,dc=edu
production:  
  host: dirapps.aset.psu.edu
  port: 389
  base: dc=psu,dc=edu
  group_base: dc=psu,dc=edu
